export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"


export const CHANGE_MODEL="CHANGE_MODEL"
export const GET_MODELS_SUCCESS="GET_MODELS_SUCCESS"

export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"

export const ADD_TO_CART="ADD_TO_CART"
export const ADD_TO_CART_QUANTITY="ADD_TO_CART_QUANTITY"

export const CHANGE_SEARCH="CHANGE_SEARCH"
export const GET_SEARCH_SUCCESS="GET_SEARCH_SUCCESS"

